# Dickey-Fuller and DF-GLS Tests
## Write test summaries to plain text file
file_df <- file("exports/dickey-fuller-gls-results.txt", open = "wt")
sink(file_df)
sink(file_df, type="message")

## Dickey-Fuller, no constant and no trend
print("Fatalities, DF w/out constant, w/out trend")
print(summary(ur.df(count_df_sort$ev_year_fat, type="none", lags=0, selectlags="Fixed")))
print("Accidents Total, DF w/out constant, w/out trend")
print(summary(ur.df(count_df_sort$ev_year_t, type="none", lags=0, selectlags="Fixed")))
print("Accidents Fatal, DF w/out constant, w/out trend")
print(summary(ur.df(count_df_sort$ev_year_f, type="none", lags=0, selectlags="Fixed")))
print("Private Pilots, DF w/out constant, w/out trend")
print(summary(ur.df(count_df_sort$private_pilots_10k, type="none", lags=0, selectlags="Fixed")))
print("Avgas Consumption, DF w/out constant, w/out trend")
print(summary(ur.df(count_df_sort$avgas_10k, type="none", lags=0, selectlags="Fixed")))
print("Flight Hours, DF w/out constant, w/out trend")
print(summary(ur.df(count_df_sort$flighthours_100k, type="none", lags=0, selectlags="Fixed")))
print("Pilots Total, DF w/out constant, w/out trend")
print(summary(ur.df(count_df_sort$pilots_10k, type="none", lags=0, selectlags="Fixed")))

## Dickey-Fuller, constant and no trend
print("Fatalities, DF w/ constant, w/out trend")
print(summary(ur.df(count_df_sort$ev_year_fat, type="drift", lags=0, selectlags="Fixed")))
print("Accidents Total, DF w/ constant, w/out trend")
print(summary(ur.df(count_df_sort$ev_year_t, type="drift", lags=0, selectlags="Fixed")))
print("Accidents Fatal, DF w/ constant, w/out trend")
print(summary(ur.df(count_df_sort$ev_year_f, type="drift", lags=0, selectlags="Fixed")))
print("Private Pilots, DF w/ constant, w/out trend")
print(summary(ur.df(count_df_sort$private_pilots_10k, type="drift", lags=0, selectlags="Fixed")))
print("Avgas Consumption, DF w/ constant, w/out trend")
print(summary(ur.df(count_df_sort$avgas_10k, type="drift", lags=0, selectlags="Fixed")))
print("Flight Hours, DF w/ constant, w/out trend")
print(summary(ur.df(count_df_sort$flighthours_100k, type="drift", lags=0, selectlags="Fixed")))
print("Pilots Total, DF w/ constant, w/out trend")
print(summary(ur.df(count_df_sort$pilots_10k, type="drift", lags=0, selectlags="Fixed")))

## DF-GLS Test, or Elliott, Rothenberg & Stock Unit Root Test
print("Fatalities, DF-GLS w/ constant, w/out trend")
print(summary(ur.ers(count_df_sort$ev_year_fat, type="DF-GLS", model="constant", lag.max=0)))
print("Accidents Total, DF-GLS w/ constant, w/out trend")
print(summary(ur.ers(count_df_sort$ev_year_t, type="DF-GLS", model="constant", lag.max=0)))
print("Accidents Fatal, DF-GLS w/ constant, w/out trend")
print(summary(ur.ers(count_df_sort$ev_year_f, type="DF-GLS", model="constant", lag.max=0)))
print("Private Pilots, DF-GLS w/ constant, w/out trend")
print(summary(ur.ers(count_df_sort$private_pilots_10k, type="DF-GLS", model="constant", lag.max=0)))
print("Avgas Consumption, DF-GLS w/ constant, w/out trend")
print(summary(ur.ers(count_df_sort$avgas_10k, type="DF-GLS", model="constant", lag.max=0)))
print("Flight Hours, DF-GLS w/ constant, w/out trend")
print(summary(ur.ers(count_df_sort$flighthours_100k, type="DF-GLS", model="constant", lag.max=0)))
print("Pilots Total, DF-GLS w/ constant, w/out trend")
print(summary(ur.ers(count_df_sort$pilots_10k, type="DF-GLS", model="constant", lag.max=0)))

sink()
