SELECT 'Importing Aircraft data';
DROP TABLE IF EXISTS `aircraft`;
CREATE TABLE `aircraft` (
  `ev_id` VARCHAR(14) NOT NULL,
  `aircraft_key` INT NOT NULL,
  `aircraft_id` VARCHAR(16) NOT NULL UNIQUE,
  `pilot_id` VARCHAR(19) NOT NULL,
  `regis_no` VARCHAR(11) DEFAULT NULL,
  `ntsb_no` VARCHAR(11) NOT NULL UNIQUE,
  `acft_missing` CHAR(1) DEFAULT NULL,
  `far_part` CHAR(4) NOT NULL,
  `flt_plan_filed` CHAR(4) DEFAULT NULL,
  `flight_plan_activated` CHAR(1) DEFAULT NULL,
  `damage` CHAR(4) DEFAULT NULL,
  `acft_fire` CHAR(4) DEFAULT NULL,
  `acft_expl` CHAR(4) DEFAULT NULL,
  `acft_make` VARCHAR(30) DEFAULT NULL,
  `acft_model` VARCHAR(20) DEFAULT NULL,
  `acft_series` VARCHAR(10) DEFAULT NULL, 
  `acft_serial_no` VARCHAR(20) DEFAULT NULL,
  `cert_max_gr_wt` INT DEFAULT NULL,
  `acft_category` CHAR(4) DEFAULT NULL,
  `acft_reg_cls` CHAR(4) DEFAULT NULL,
  `homebuilt` CHAR(3) DEFAULT NULL,
  `fc_seats` INT DEFAULT NULL,
  `cc_seats` INT DEFAULT NULL,
  `pax_seats` INT DEFAULT NULL,
  `total_seats` SMALLINT DEFAULT NULL,
  `num_eng` TINYINT DEFAULT NULL,
  `fixed_retractable` CHAR(4) DEFAULT NULL,
  `type_last_insp` CHAR(4) DEFAULT NULL,
  `date_last_insp` DATETIME DEFAULT NULL,
  `afm_hrs_last_insp` REAL DEFAULT NULL,
  `afm_hrs` REAL DEFAULT NULL,
  `elt_install` CHAR(1) DEFAULT NULL,
  `elt_oper` CHAR(1) DEFAULT NULL,
  `elt_aided_loc_ev` CHAR(1) DEFAULT NULL,
  `elt_type` CHAR(4) DEFAULT NULL,
  `owner_acft` VARCHAR(50) DEFAULT NULL,
  `owner_street` VARCHAR(50) DEFAULT NULL,
  `owner_city` VARCHAR(50) DEFAULT NULL,
  `owner_state` CHAR(2) DEFAULT NULL,
  `owner_country` CHAR(4) DEFAULT NULL,
  `owner_zip` VARCHAR(10) DEFAULT NULL,
  `oper_individual_name` CHAR(1) DEFAULT NULL,
  `oper_name` VARCHAR(50) DEFAULT NULL,
  `oper_same` CHAR(1) DEFAULT NULL,
  `oper_dba` VARCHAR(50) DEFAULT NULL,
  `oper_addr_same` CHAR(1) DEFAULT NULL,
  `oper_street` VARCHAR(50) DEFAULT NULL,
  `oper_city` VARCHAR(50) DEFAULT NULL,
  `oper_state` CHAR(2) DEFAULT NULL,
  `oper_country` CHAR(4) DEFAULT NULL,
  `oper_zip` VARCHAR(10) DEFAULT NULL,
  `oper_code` CHAR(4) DEFAULT NULL,
  `certs_held` CHAR(1) DEFAULT NULL,
  `oprtng_cert` CHAR(3) DEFAULT NULL,
  `oper_cert` CHAR(4) DEFAULT NULL,
  `oper_cert_num` VARCHAR(11) DEFAULT NULL,
  `oper_sched` CHAR(4) DEFAULT NULL,
  `oper_dom_int` CHAR(3) DEFAULT NULL,
  `oper_pax_cargo` CHAR(4) DEFAULT NULL,
  `type_fly` CHAR(4) DEFAULT NULL,
  `second_pilot` CHAR(1) DEFAULT NULL,
  `dprt_pt_same_ev` CHAR(1) DEFAULT NULL,
  `dprt_apt_id` CHAR(4) DEFAULT NULL,
  `dprt_city` VARCHAR(50) DEFAULT NULL,
  `dprt_state` CHAR(2) DEFAULT NULL,
  `dprt_country` CHAR(3) DEFAULT NULL,
  `dprt_time` SMALLINT DEFAULT NULL,
  `dprt_timezn` CHAR(3) DEFAULT NULL,
  `dest_same_local` CHAR(4) DEFAULT NULL,
  `dest_apt_id` CHAR(4) DEFAULT NULL,
  `dest_city` VARCHAR(50) DEFAULT NULL,
  `dest_state` CHAR(2) DEFAULT NULL,
  `dest_country` CHAR(3) DEFAULT NULL,
  `phase_flt_spec` INT DEFAULT NULL,
  `report_to_icao` CHAR(1) DEFAULT NULL,
  `evacuation` CHAR(1) DEFAULT NULL,
  `aircraft_lchg_date` DATETIME DEFAULT NULL,
  `aircraft_lchg_userid` VARCHAR(18) DEFAULT NULL,
  `afm_hrs_since` CHAR(4) DEFAULT NULL,
  `rwy_num` VARCHAR(4) DEFAULT NULL,
  `rwy_len` INT DEFAULT NULL,
  `rwy_width` INT DEFAULT NULL,
  `site_seeing` CHAR(1) DEFAULT NULL,
  `air_medical` CHAR(1) DEFAULT NULL,
  `med_type_flight` VARCHAR(15) DEFAULT NULL,
  `acft_year` DATETIME DEFAULT NULL,
  `fuel_on_board` VARCHAR(4) DEFAULT NULL,
  `commercial_space_flight` INT DEFAULT NULL,
  `unmanned` INT DEFAULT NULL,
  `ifr_equipped_cert` INT DEFAULT NULL,
  `elt_mounted_aircraft` INT DEFAULT NULL,
  `elt_connected_antenna` INT DEFAULT NULL,
  `elt_manufacturer` VARCHAR(4) DEFAULT NULL,
  `elt_model` VARCHAR(4) DEFAULT NULL,
  `elt_reason_other` VARCHAR(4) DEFAULT NULL,
  `ev_type` VARCHAR(3) DEFAULT NULL,
  `ev_date` DATE DEFAULT NULL,
  `ev_dow` VARCHAR(2) DEFAULT NULL,
  `ev_time` TIME DEFAULT NULL,
  `ev_tmzn` VARCHAR(3) DEFAULT NULL,
  `ev_city` VARCHAR(50) DEFAULT NULL,
  `ev_state` VARCHAR(2) DEFAULT NULL,
  `ev_country` VARCHAR(4) DEFAULT NULL,
  `ev_site_zipcode` VARCHAR(10) DEFAULT NULL,
  `ev_year` SMALLINT DEFAULT NULL,
  `ev_month` TINYINT DEFAULT NULL,
  `mid_air` VARCHAR(1) DEFAULT NULL,
  `on_ground_collision` VARCHAR(1) DEFAULT NULL,
  `latitude` VARCHAR(7) DEFAULT NULL,
  `longitude` VARCHAR(8) DEFAULT NULL,
  `latlong_acq` VARCHAR(4) DEFAULT NULL,
  `apt_name` VARCHAR(30) DEFAULT NULL,
  `ev_nr_apt_id` VARCHAR(4) DEFAULT NULL,
  `ev_nr_apt_loc` VARCHAR(4) DEFAULT NULL,
  `apt_dist` REAL DEFAULT NULL,
  `apt_dir` SMALLINT DEFAULT NULL,
  `apt_elev` SMALLINT DEFAULT NULL,
  `wx_brief_comp` VARCHAR(4) DEFAULT NULL,
  `wx_src_iic` VARCHAR(4) DEFAULT NULL,
  `wx_obs_time` SMALLINT DEFAULT NULL,
  `wx_obs_dir` SMALLINT DEFAULT NULL,
  `wx_obs_fac_id` VARCHAR(4) DEFAULT NULL,
  `wx_obs_elev` INT DEFAULT NULL,
  `wx_obs_dist` SMALLINT DEFAULT NULL,
  `wx_obs_tmzn` VARCHAR(3) DEFAULT NULL,
  `light_cond` VARCHAR(4) DEFAULT NULL,
  `sky_cond_nonceil` VARCHAR(4) DEFAULT NULL,
  `sky_nonceil_ht` INT DEFAULT NULL,
  `sky_ceil_ht` INT DEFAULT NULL,
  `sky_cond_ceil` VARCHAR(4) DEFAULT NULL,
  `vis_rvr` REAL DEFAULT NULL,
  `vis_rvv` SMALLINT DEFAULT NULL,
  `vis_sm` REAL DEFAULT NULL,
  `wx_temp` SMALLINT DEFAULT NULL,
  `wx_dew_pt` SMALLINT DEFAULT NULL,
  `wind_dir_deg` SMALLINT DEFAULT NULL,
  `wind_dir_ind` VARCHAR(1) DEFAULT NULL,
  `wind_vel_kts` TINYINT DEFAULT NULL,
  `wind_vel_ind` VARCHAR(4) DEFAULT NULL,
  `gust_ind` VARCHAR(1) DEFAULT NULL,
  `gust_kts` SMALLINT DEFAULT NULL,
  `altimeter` REAL DEFAULT NULL,
  `wx_dens_alt` INT DEFAULT NULL,
  `wx_int_precip` VARCHAR(3) DEFAULT NULL,
  `ev_highest_injury` VARCHAR(4) DEFAULT NULL,
  `inj_f_grnd` SMALLINT DEFAULT NULL,
  `inj_m_grnd` SMALLINT DEFAULT NULL,
  `inj_s_grnd` SMALLINT DEFAULT NULL,
  `inj_tot_f` SMALLINT DEFAULT NULL,
  `inj_tot_m` SMALLINT DEFAULT NULL,
  `inj_tot_n` SMALLINT DEFAULT NULL,
  `inj_tot_s` SMALLINT DEFAULT NULL,
  `inj_tot_t` SMALLINT DEFAULT NULL,
  `invest_agy` VARCHAR(1) DEFAULT NULL,
  `ntsb_docket` INT DEFAULT NULL,
  `ntsb_notf_from` VARCHAR(30) DEFAULT NULL,
  `ntsb_notf_date` DATETIME DEFAULT NULL,
  `ntsb_notf_tm` SMALLINT DEFAULT NULL,
  `fiche_number` VARCHAR(5) DEFAULT NULL,
  `events_lchg_date` DATETIME DEFAULT NULL,
  `events_lchg_userid` VARCHAR(18) DEFAULT NULL,
  `wx_cond_basic` VARCHAR(3) DEFAULT NULL,
  `faa_dist_office` VARCHAR(50) DEFAULT NULL,
  `prop_dmg` CHAR(60) DEFAULT NULL,
  `vis_restrct` CHAR(60) DEFAULT NULL,
  `wx_brief_mthd` CHAR(30) DEFAULT NULL,
  `wx_brief_src` CHAR(70) DEFAULT NULL,
  `wx_cond` CHAR(145) DEFAULT NULL,
  `pilot_no` TINYINT NOT NULL,
  `pilot_age` TINYINT DEFAULT NULL,
  `pilot_sex` CHAR(1) DEFAULT NULL,
  `pilot_city` VARCHAR(15) DEFAULT NULL,
  `pilot_res_state` CHAR(2) DEFAULT NULL,
  `pilot_res_country` CHAR(4) DEFAULT NULL,
  `pilot_med_certf` CHAR(4) DEFAULT NULL,
  `pilot_med_crtf_vldty` CHAR(4) DEFAULT NULL,
  `pilot_date_lst_med` DATETIME DEFAULT NULL,
  `pilot_rat_endorse` CHAR(1) DEFAULT NULL,
  `pilot_inj_level` CHAR(4) DEFAULT NULL,
  `pilot_seatbelts_used` CHAR(1) DEFAULT NULL,
  `pilot_shldr_harn_used` CHAR(1) DEFAULT NULL,
  `pilot_tox_perf` CHAR(1) DEFAULT NULL,
  `pilot_seat_occ_pic` CHAR(4) DEFAULT NULL,
  `pilot_pc_profession` CHAR(4) DEFAULT NULL,
  `pilot_bfr` CHAR(1) DEFAULT NULL,
  `pilot_bfr_date` DATETIME DEFAULT NULL,
  `pilot_ft_as_of` DATETIME DEFAULT NULL,
  `pilot_flight_crew_lchg_date` DATETIME DEFAULT NULL,
  `pilot_flight_crew_lchg_userid` VARCHAR(18) DEFAULT NULL,
  `pilot_cert_code` CHAR(55) DEFAULT NULL,
  `pilot_rat_airpln` CHAR(25) DEFAULT NULL,
  `pilot_rat_instruct` CHAR(50) DEFAULT NULL,
  `pilot_rat_instrum` CHAR(20) DEFAULT NULL,
  `pilot_rat_roto` CHAR(35) DEFAULT NULL,
  `pilot_flight_hours_l24h_all` REAL DEFAULT NULL,
  `pilot_flight_hours_l30d_all` REAL DEFAULT NULL,
  `pilot_flight_hours_l90d_all` REAL DEFAULT NULL,
  `pilot_flight_hours_pic_all` REAL DEFAULT NULL,
  `pilot_flight_hours_totl_all` REAL DEFAULT NULL,
  `pilot_flight_hours_l24h_make` REAL DEFAULT NULL,
  `pilot_flight_hours_l30d_make` REAL DEFAULT NULL,
  `pilot_flight_hours_l90d_make` REAL DEFAULT NULL,
  `pilot_flight_hours_pic_make` REAL DEFAULT NULL,
  `pilot_flight_hours_totl_make` REAL DEFAULT NULL,
  PRIMARY KEY (`aircraft_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

LOAD DATA INFILE '/tmp/aircraft.csv' INTO TABLE `aircraft`
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@evid, @aircraftkey, @regisno, @ntsbno, @acftmissing, @farpart, @fltplanfiled, @flightplanactivated, @damage, @acftfire, @acftexpl, @acftmake, @acftmodel, @acftseries, @acftserialno, @certmaxgrwt, @acftcategory, @acftregcls, @homebuilt, @fcseats, @ccseats, @paxseats, @totalseats, @numeng, @fixedretractable, @typelastinsp, @datelastinsp, @afmhrslastinsp, @afmhrs, @eltinstall, @eltoper, @eltaidedlocev, @elttype, @owneracft, @ownerstreet, @ownercity, @ownerstate, @ownercountry, @ownerzip, @operindividualname, @opername, @opersame, @operdba, @operaddrsame, @operstreet, @opercity, @operstate, @opercountry, @operzip, @opercode, @certsheld, @oprtngcert, @opercert, @opercertnum, @opersched, @operdomint, @operpaxcargo, @typefly, @secondpilot, @dprtptsameev, @dprtaptid, @dprtcity, @dprtstate, @dprtcountry, @dprttime, @dprttimezn, @destsamelocal, @destaptid, @destcity, @deststate, @destcountry, @phasefltspec, @reporttoicao, @evacuation, @lchgdate, @lchguserid, @afmhrssince, @rwynum, @rwylen, @rwywidth, @siteseeing, @airmedical, @medtypeflight, @acftyear, @fuelonboard, @commercialspaceflight, @unmanned, @ifrequippedcert, @eltmountedaircraft, @eltconnectedantenna, @eltmanufacturer, @eltmodel, @eltreasonother)
SET
  `ev_id` = TRIM(NULLIF(@evid, '')),
  `aircraft_key` = TRIM(NULLIF(@aircraftkey, '')),
  `aircraft_id` = CONCAT(@evid, '-', @aircraftkey),
  `regis_no` = TRIM(NULLIF(@regisno, '')),
  `ntsb_no` = TRIM(NULLIF(@ntsbno, '')),
  `acft_missing` = TRIM(NULLIF(@acftmissing, '')),
  `far_part` = TRIM(NULLIF(@farpart, '')),
  `flt_plan_filed` = TRIM(NULLIF(@fltplanfiled, '')),
  `flight_plan_activated` = TRIM(NULLIF(@flightplanactivated, '')),
  `damage` = TRIM(NULLIF(@damage, '')),
  `acft_fire` = TRIM(NULLIF(@acftfire, '')),
  `acft_expl` = TRIM(NULLIF(@acftexpl, '')),
  `acft_make` = TRIM(NULLIF(@acftmake, '')),
  `acft_model` = TRIM(NULLIF(@acftmodel, '')),
  `acft_series` = TRIM(NULLIF(@acftseries, '')),
  `acft_serial_no` = TRIM(NULLIF(@acftserialno, '')),
  `cert_max_gr_wt` = TRIM(NULLIF(@certmaxgrwt, '')),
  `acft_category` = TRIM(NULLIF(@acftcategory, '')),
  `acft_reg_cls` = TRIM(NULLIF(@acftregcls, '')),
  `homebuilt` = TRIM(NULLIF(@homebuilt, '')),
  `fc_seats` = TRIM(NULLIF(@fcseats, '')),
  `cc_seats` = TRIM(NULLIF(@ccseats, '')),
  `pax_seats` = TRIM(NULLIF(@paxseats, '')),
  `total_seats` = TRIM(NULLIF(@totalseats, '')),
  `num_eng` = TRIM(NULLIF(@numeng, '')),
  `fixed_retractable` = TRIM(NULLIF(@fixedretractable, '')),
  `type_last_insp` = TRIM(NULLIF(@typelastinsp, '')),
  `date_last_insp` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@datelastinsp, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `afm_hrs_last_insp` = TRIM(NULLIF(@afmhrslastinsp, '')),
  `afm_hrs` = TRIM(NULLIF(@afmhrs, '')),
  `elt_install` = TRIM(NULLIF(@eltinstall, '')),
  `elt_oper` = TRIM(NULLIF(@eltoper, '')),
  `elt_aided_loc_ev` = TRIM(NULLIF(@eltaidedlocev, '')),
  `elt_type` = TRIM(NULLIF(@elttype, '')),
  `owner_acft` = REPLACE(TRIM(NULLIF(@owneracft, '')), '"', '\''),
  `owner_street` = TRIM(NULLIF(@ownerstreet, '')),
  `owner_city` = TRIM(NULLIF(@ownercity, '')),
  `owner_state` = TRIM(NULLIF(@ownerstate, '')),
  `owner_country` = TRIM(NULLIF(@ownercountry, '')),
  `owner_zip` = TRIM(NULLIF(@ownerzip, '')),
  `oper_individual_name` = TRIM(NULLIF(@operindividualname, '')),
  `oper_name` = TRIM(NULLIF(@opername, '')),
  `oper_same` = TRIM(NULLIF(@opersame, '')),
  `oper_dba` = TRIM(NULLIF(@operdba, '')),
  `oper_addr_same` = TRIM(NULLIF(@operaddrsame, '')),
  `oper_street` = TRIM(NULLIF(@operstreet, '')),
  `oper_city` = TRIM(NULLIF(@opercity, '')),
  `oper_state` = TRIM(NULLIF(@operstate, '')),
  `oper_country` = TRIM(NULLIF(@opercountry, '')),
  `oper_zip` = TRIM(NULLIF(@operzip, '')),
  `oper_code` = TRIM(NULLIF(@opercode, '')),
  `certs_held` = TRIM(NULLIF(@certsheld, '')),
  `oprtng_cert` = TRIM(NULLIF(@oprtngcert, '')),
  `oper_cert` = TRIM(NULLIF(@opercert, '')),
  `oper_cert_num` = TRIM(NULLIF(@opercertnum, '')),
  `oper_sched` = TRIM(NULLIF(@opersched, '')),
  `oper_dom_int` = TRIM(NULLIF(@operdomint, '')),
  `oper_pax_cargo` = TRIM(NULLIF(@operpaxcargo, '')),
  `type_fly` = TRIM(NULLIF(@typefly, '')),
  `second_pilot` = TRIM(NULLIF(@secondpilot, '')),
  `dprt_pt_same_ev` = TRIM(NULLIF(@dprtptsameev, '')),
  `dprt_apt_id` = TRIM(NULLIF(@dprtaptid, '')),
  `dprt_city` = TRIM(NULLIF(@dprtcity, '')),
  `dprt_state` = TRIM(NULLIF(@dprtstate, '')),
  `dprt_country` = TRIM(NULLIF(@dprtcountry, '')),
  `dprt_time` = TRIM(NULLIF(@dprttime, '')),
  `dprt_timezn` = TRIM(NULLIF(@dprttimezn, '')),
  `dest_same_local` = TRIM(NULLIF(@destsamelocal, '')),
  `dest_apt_id` = TRIM(NULLIF(@destaptid, '')),
  `dest_city` = TRIM(NULLIF(@destcity, '')),
  `dest_state` = TRIM(NULLIF(@deststate, '')),
  `dest_country` = TRIM(NULLIF(@destcountry, '')),
  `phase_flt_spec` = TRIM(NULLIF(@phasefltspec, '')),
  `report_to_icao` = TRIM(NULLIF(@reporttoicao, '')),
  `evacuation` = TRIM(NULLIF(@evacuation, '')),
  `aircraft_lchg_date` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@lchgdate, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `aircraft_lchg_userid` = TRIM(NULLIF(@lchguserid, '')),
  `afm_hrs_since` = TRIM(NULLIF(@afmhrssince, '')),
  `rwy_num` = TRIM(NULLIF(@rwynum, '')),
  `rwy_len` = TRIM(NULLIF(@rwylen, '')),
  `rwy_width` = TRIM(NULLIF(@rwywidth, '')),
  `site_seeing` = TRIM(NULLIF(@siteseeing, '')),
  `air_medical` = TRIM(NULLIF(@airmedical, '')),
  `med_type_flight` = TRIM(NULLIF(@medtypeflight, '')),
  `acft_year` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@acftyear, '')), '%Y'), '%Y-%m-%d'),
  `fuel_on_board` = TRIM(NULLIF(@fuelonboard, '')),
  `commercial_space_flight` = TRIM(NULLIF(@commercialspaceflight, '')),
  `unmanned` = TRIM(NULLIF(@unmanned, '')),
  `ifr_equipped_cert` = TRIM(NULLIF(@ifrequippedcert, '')),
  `elt_mounted_aircraft` = TRIM(NULLIF(@eltmountedaircraft, '')),
  `elt_connected_antenna` = TRIM(NULLIF(@eltconnectedantenna, '')),
  `elt_manufacturer` = TRIM(NULLIF(@eltmanufacturer, '')),
  `elt_model` = TRIM(NULLIF(@eltmodel, '')),
  `elt_reason_other` = TRIM(NULLIF(@eltreasonother, ''));

SELECT 'Importing Events data';
DROP TABLE IF EXISTS `events`;
CREATE TABLE `events` (
  `ev_id` VARCHAR(14) NOT NULL UNIQUE,
  `ntsb_no` VARCHAR(10) NOT NULL,
  `ev_type` VARCHAR(3) DEFAULT NULL,
  `ev_date` DATE DEFAULT NULL,
  `ev_dow` VARCHAR(2) DEFAULT NULL,
  `ev_time` TIME DEFAULT NULL,
  `ev_tmzn` VARCHAR(3) DEFAULT NULL,
  `ev_city` VARCHAR(50) DEFAULT NULL,
  `ev_state` VARCHAR(2) DEFAULT NULL,
  `ev_country` VARCHAR(4) DEFAULT NULL,
  `ev_site_zipcode` VARCHAR(10) DEFAULT NULL,
  `ev_year` SMALLINT DEFAULT NULL,
  `ev_month` TINYINT DEFAULT NULL,
  `mid_air` VARCHAR(1) DEFAULT NULL,
  `on_ground_collision` VARCHAR(1) DEFAULT NULL,
  `latitude` VARCHAR(7) DEFAULT NULL,
  `longitude` VARCHAR(8) DEFAULT NULL,
  `latlong_acq` VARCHAR(4) DEFAULT NULL,
  `apt_name` VARCHAR(30) DEFAULT NULL,
  `ev_nr_apt_id` VARCHAR(4) DEFAULT NULL,
  `ev_nr_apt_loc` VARCHAR(4) DEFAULT NULL,
  `apt_dist` REAL DEFAULT NULL,
  `apt_dir` SMALLINT DEFAULT NULL,
  `apt_elev` SMALLINT DEFAULT NULL,
  `wx_brief_comp` VARCHAR(4) DEFAULT NULL,
  `wx_src_iic` VARCHAR(4) DEFAULT NULL,
  `wx_obs_time` SMALLINT DEFAULT NULL,
  `wx_obs_dir` SMALLINT DEFAULT NULL,
  `wx_obs_fac_id` VARCHAR(4) DEFAULT NULL,
  `wx_obs_elev` INT DEFAULT NULL,
  `wx_obs_dist` SMALLINT DEFAULT NULL,
  `wx_obs_tmzn` VARCHAR(3) DEFAULT NULL,
  `light_cond` VARCHAR(4) DEFAULT NULL,
  `sky_cond_nonceil` VARCHAR(4) DEFAULT NULL,
  `sky_nonceil_ht` INT DEFAULT NULL,
  `sky_ceil_ht` INT DEFAULT NULL,
  `sky_cond_ceil` VARCHAR(4) DEFAULT NULL,
  `vis_rvr` REAL DEFAULT NULL,
  `vis_rvv` SMALLINT DEFAULT NULL,
  `vis_sm` REAL DEFAULT NULL,
  `wx_temp` SMALLINT DEFAULT NULL,
  `wx_dew_pt` SMALLINT DEFAULT NULL,
  `wind_dir_deg` SMALLINT DEFAULT NULL,
  `wind_dir_ind` VARCHAR(1) DEFAULT NULL,
  `wind_vel_kts` TINYINT DEFAULT NULL,
  `wind_vel_ind` VARCHAR(4) DEFAULT NULL,
  `gust_ind` VARCHAR(1) DEFAULT NULL,
  `gust_kts` SMALLINT DEFAULT NULL,
  `altimeter` REAL DEFAULT NULL,
  `wx_dens_alt` INT DEFAULT NULL,
  `wx_int_precip` VARCHAR(3) DEFAULT NULL,
  `ev_highest_injury` VARCHAR(4) DEFAULT NULL,
  `inj_f_grnd` SMALLINT DEFAULT NULL,
  `inj_m_grnd` SMALLINT DEFAULT NULL,
  `inj_s_grnd` SMALLINT DEFAULT NULL,
  `inj_tot_f` SMALLINT DEFAULT NULL,
  `inj_tot_m` SMALLINT DEFAULT NULL,
  `inj_tot_n` SMALLINT DEFAULT NULL,
  `inj_tot_s` SMALLINT DEFAULT NULL,
  `inj_tot_t` SMALLINT DEFAULT NULL,
  `invest_agy` VARCHAR(1) DEFAULT NULL,
  `ntsb_docket` INT DEFAULT NULL,
  `ntsb_notf_from` VARCHAR(30) DEFAULT NULL,
  `ntsb_notf_date` DATETIME DEFAULT NULL,
  `ntsb_notf_tm` SMALLINT DEFAULT NULL,
  `fiche_number` VARCHAR(5) DEFAULT NULL,
  `events_lchg_date` DATETIME DEFAULT NULL,
  `events_lchg_userid` VARCHAR(18) DEFAULT NULL,
  `wx_cond_basic` VARCHAR(3) DEFAULT NULL,
  `faa_dist_office` VARCHAR(50) DEFAULT NULL,
  `prop_dmg` CHAR(60) DEFAULT NULL,
  `vis_restrct` CHAR(60) DEFAULT NULL,
  `wx_brief_mthd` CHAR(30) DEFAULT NULL,
  `wx_brief_src` CHAR(70) DEFAULT NULL,
  `wx_cond` CHAR(145) DEFAULT NULL,
  PRIMARY KEY (`ev_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

LOAD DATA INFILE '/tmp/events.csv' INTO TABLE `events`
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@evid, @ntsbno, @evtype, @evdate, @evdow, @evtime, @evtmzn, @evcity, @evstate, @evcountry, @evsitezipcode, @evyear, @evmonth, @midair, @ongroundcollision, @latitude, @longitude, @latlongacq, @aptname, @evnraptid, @evnraptloc, @aptdist, @aptdir, @aptelev, @wxbriefcomp, @wxsrciic, @wxobstime, @wxobsdir, @wxobsfacid, @wxobselev, @wxobsdist, @wxobstmzn, @lightcond, @skycondnonceil, @skynonceilht, @skyceilht, @skycondceil, @visrvr, @visrvv, @vissm, @wxtemp, @wxdewpt, @winddirdeg, @winddirind, @windvelkts, @windvelind, @gustind, @gustkts, @altimeter, @wxdensalt, @wxintprecip, @evhighestinjury, @injfgrnd, @injmgrnd, @injsgrnd, @injtotf, @injtotm, @injtotn, @injtots, @injtott, @investagy, @ntsbdocket, @ntsbnotffrom, @ntsbnotfdate, @ntsbnotftm, @fichenumber, @lchgdate, @lchguserid, @wxcondbasic, @faadistoffice)
SET
  `ev_id` = TRIM(NULLIF(@evid, '')),
  `ntsb_no` = TRIM(NULLIF(@ntsbno, '')),
  `ev_type` = TRIM(NULLIF(@evtype, '')),
  `ev_date` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@evdate, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `ev_dow` = TRIM(NULLIF(@evdow, '')),
  `ev_time` = TIME_FORMAT(TRIM(NULLIF(CONCAT(@evtime, '00'), '00')), '%T'),
  `ev_tmzn` = TRIM(NULLIF(@evtmzn, '')),
  `ev_city` = TRIM(NULLIF(@evcity, '')),
  `ev_state` = TRIM(NULLIF(@evstate, '')),
  `ev_country` = TRIM(NULLIF(@evcountry, '')),
  `ev_site_zipcode` = TRIM(NULLIF(@evsitezipcode, '')),
  `ev_year` = TRIM(NULLIF(@evyear, '')),
  `ev_month` = TRIM(NULLIF(@evmonth, '')),
  `mid_air` = TRIM(NULLIF(@midair, '')),
  `on_ground_collision` = TRIM(NULLIF(@ongroundcollision, '')),
  `latitude` = TRIM(NULLIF(@latitude, '')),
  `longitude` = TRIM(NULLIF(@longitude, '')),
  `latlong_acq` = TRIM(NULLIF(@latlongacq, '')),
  `apt_name` = TRIM(NULLIF(@aptname, '')),
  `ev_nr_apt_id` = TRIM(NULLIF(@evnraptid, '')),
  `ev_nr_apt_loc` = TRIM(NULLIF(@evnraptloc, '')),
  `apt_dist` = TRIM(NULLIF(@aptdist, '')),
  `apt_dir` = TRIM(NULLIF(@aptdir, '')),
  `apt_elev` = TRIM(NULLIF(@aptelev, '')),
  `wx_brief_comp` = TRIM(NULLIF(@wxbriefcomp, '')),
  `wx_src_iic` = TRIM(NULLIF(@wxsrciic, '')),
  `wx_obs_time` = TRIM(NULLIF(@wxobstime, '')),
  `wx_obs_dir` = TRIM(NULLIF(@wxobsdir, '')),
  `wx_obs_fac_id` = TRIM(NULLIF(@wxobsfacid, '')),
  `wx_obs_elev` = TRIM(NULLIF(@wxobselev, '')),
  `wx_obs_dist` = TRIM(NULLIF(@wxobsdist, '')),
  `wx_obs_tmzn` = TRIM(NULLIF(@wxobstmzn, '')),
  `light_cond` = TRIM(NULLIF(@lightcond, '')),
  `sky_cond_nonceil` = TRIM(NULLIF(@skycondnonceil, '')),
  `sky_nonceil_ht` = TRIM(NULLIF(@skynonceilht, '')),
  `sky_ceil_ht` = TRIM(NULLIF(@skyceilht, '')),
  `sky_cond_ceil` = TRIM(NULLIF(@skycondceil, '')),
  `vis_rvr` = TRIM(NULLIF(@visrvr, '')),
  `vis_rvv` = TRIM(NULLIF(@visrvv, '')),
  `vis_sm` = TRIM(NULLIF(@vissm, '')),
  `wx_temp` = TRIM(NULLIF(@wxtemp, '')),
  `wx_dew_pt` = TRIM(NULLIF(@wxdewpt, '')),
  `wind_dir_deg` = TRIM(NULLIF(@winddirdeg, '')),
  `wind_dir_ind` = TRIM(NULLIF(@winddirind, '')),
  `wind_vel_kts` = TRIM(NULLIF(@windvelkts, '')),
  `wind_vel_ind` = TRIM(NULLIF(@windvelind, '')),
  `gust_ind` = TRIM(NULLIF(@gustind, '')),
  `gust_kts` = TRIM(NULLIF(@gustkts, '')),
  `altimeter` = TRIM(NULLIF(@altimeter, '')),
  `wx_dens_alt` = TRIM(NULLIF(@wxdensalt, '')),
  `wx_int_precip` = TRIM(NULLIF(@wxintprecip, '')),
  `ev_highest_injury` = TRIM(NULLIF(@evhighestinjury, '')),
  `inj_f_grnd` = TRIM(NULLIF(@injfgrnd, '')),
  `inj_m_grnd` = TRIM(NULLIF(@injmgrnd, '')),
  `inj_s_grnd` = TRIM(NULLIF(@injsgrnd, '')),
  `inj_tot_f` = TRIM(NULLIF(@injtotf, '')),
  `inj_tot_m` = TRIM(NULLIF(@injtotm, '')),
  `inj_tot_n` = TRIM(NULLIF(@injtotn, '')),
  `inj_tot_s` = TRIM(NULLIF(@injtots, '')),
  `inj_tot_t` = TRIM(NULLIF(@injtott, '')),
  `invest_agy` = TRIM(NULLIF(@investagy, '')),
  `ntsb_docket` = TRIM(NULLIF(@ntsbdocket, '')),
  `ntsb_notf_from` = TRIM(NULLIF(@ntsbnotffrom, '')),
  `ntsb_notf_date` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@ntsb_notf_date, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `ntsb_notf_tm` = TRIM(NULLIF(@ntsbnotftm, '')),
  `fiche_number` = TRIM(NULLIF(@fichenumber, '')),
  `events_lchg_date` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@lchgdate, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `events_lchg_userid` = TRIM(NULLIF(@lchguserid, '')),
  `wx_cond_basic` = TRIM(NULLIF(@wxcondbasic, '')),
  `faa_dist_office` = TRIM(NULLIF(@faadistoffice, ''));

SELECT 'Importing Events detailed data';
DROP TABLE IF EXISTS `dt_events`;
CREATE TABLE `dt_events` (
  `ev_id` VARCHAR(14) NOT NULL,
  `col_name` CHAR(20) NOT NULL,
  `code` CHAR(4) NOT NULL,
  `dt_events_lchg_date` DATETIME DEFAULT NULL,
  `dt_events_lchg_userid` VARCHAR(18) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

LOAD DATA INFILE '/tmp/dt_events.csv' INTO TABLE `dt_events`
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@evid, @colname, @code, @lchgdate, @lchguserid)
SET
  `ev_id` = TRIM(NULLIF(@evid, '')),
  `col_name` = TRIM(NULLIF(@colname, '')),
  `code` = TRIM(NULLIF(@code, '')),
  `dt_events_lchg_date` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@lchgdate, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `dt_events_lchg_userid` = TRIM(NULLIF(@lchguserid, ''));

SELECT 'Importing Flight Crew data';
DROP TABLE IF EXISTS `flight_crew`;
CREATE TABLE `flight_crew` (
  `ev_id` VARCHAR(14) NOT NULL,
  `aircraft_key` INT NOT NULL,
  `aircraft_id` VARCHAR(16) NOT NULL,
  `crew_no` TINYINT NOT NULL,
  `crew_id` VARCHAR(19) NOT NULL UNIQUE,
  `crew_category` CHAR(5) DEFAULT NULL,
  `crew_age` TINYINT DEFAULT NULL,
  `crew_sex` CHAR(1) DEFAULT NULL,
  `crew_city` VARCHAR(15) DEFAULT NULL,
  `crew_res_state` CHAR(2) DEFAULT NULL,
  `crew_res_country` CHAR(4) DEFAULT NULL,
  `med_certf` CHAR(4) DEFAULT NULL,
  `med_crtf_vldty` CHAR(4) DEFAULT NULL,
  `date_lst_med` DATETIME DEFAULT NULL,
  `crew_rat_endorse` CHAR(1) DEFAULT NULL,
  `crew_inj_level` CHAR(4) DEFAULT NULL,
  `seatbelts_used` CHAR(1) DEFAULT NULL,
  `shldr_harn_used` CHAR(1) DEFAULT NULL,
  `crew_tox_perf` CHAR(1) DEFAULT NULL,
  `seat_occ_pic` CHAR(4) DEFAULT NULL,
  `pc_profession` CHAR(4) DEFAULT NULL,
  `bfr` CHAR(1) DEFAULT NULL,
  `bfr_date` DATETIME DEFAULT NULL,
  `ft_as_of` DATETIME DEFAULT NULL,
  `flight_crew_lchg_date` DATETIME DEFAULT NULL,
  `flight_crew_lchg_userid` VARCHAR(18) DEFAULT NULL,
  `crew_cert_code` CHAR(55) DEFAULT NULL,
  `crew_rat_airpln` CHAR(25) DEFAULT NULL,
  `crew_rat_instruct` CHAR(50) DEFAULT NULL,
  `crew_rat_instrum` CHAR(20) DEFAULT NULL,
  `crew_rat_roto` CHAR(35) DEFAULT NULL,
  `flight_hours_l24h_all` REAL DEFAULT NULL,
  `flight_hours_l30d_all` REAL DEFAULT NULL,
  `flight_hours_l90d_all` REAL DEFAULT NULL,
  `flight_hours_pic_all` REAL DEFAULT NULL,
  `flight_hours_totl_all` REAL DEFAULT NULL,
  `flight_hours_l24h_make` REAL DEFAULT NULL,
  `flight_hours_l30d_make` REAL DEFAULT NULL,
  `flight_hours_l90d_make` REAL DEFAULT NULL,
  `flight_hours_pic_make` REAL DEFAULT NULL,
  `flight_hours_totl_make` REAL DEFAULT NULL,
  PRIMARY KEY (`crew_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

LOAD DATA INFILE '/tmp/flight_crew.csv' INTO TABLE `flight_crew`
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@evid, @aircraftkey, @crewno, @crewcategory, @crewage, @crewsex, @crewcity, @crewresstate, @crewrescountry, @medcertf, @medcrtfvldty, @datelstmed, @crewratendorse, @crewinjlevel, @seatbeltsused, @shldrharnused, @crewtoxperf, @seatoccpic, @pcprofession, @bfr, @bfrdate, @ftasof, @lchgdate, @lchguserid)
SET
  `ev_id` = TRIM(NULLIF(@evid, '')),
  `aircraft_key` = TRIM(NULLIF(@aircraftkey, '')),
  `aircraft_id` = CONCAT(@evid, '-', @aircraftkey),
  `crew_no` = TRIM(NULLIF(@crewno, '')),
  `crew_id` = CONCAT(@evid, '-', @aircraftkey, '-', @crewno),
  `crew_category` = TRIM(NULLIF(@crewcategory, '')),
  `crew_age` = TRIM(NULLIF(@crewage, '')),
  `crew_sex` = TRIM(NULLIF(@crewsex, '')),
  `crew_city` = TRIM(NULLIF(@crewcity, '')),
  `crew_res_state` = TRIM(NULLIF(@crewresstate, '')),
  `crew_res_country` = TRIM(NULLIF(@crewrescountry, '')),
  `med_certf` = TRIM(NULLIF(@medcertf, '')),
  `med_crtf_vldty` = TRIM(NULLIF(@medcrtfvldty, '')),
  `date_lst_med` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@datelstmed, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `crew_rat_endorse` = TRIM(NULLIF(@crewratendorse, '')),
  `crew_inj_level` = TRIM(NULLIF(@crewinjlevel, '')),
  `seatbelts_used` = TRIM(NULLIF(@seatbeltsused, '')),
  `shldr_harn_used` = TRIM(NULLIF(@shldrharnused, '')),
  `crew_tox_perf` = TRIM(NULLIF(@crewtoxperf, '')),
  `seat_occ_pic` = TRIM(NULLIF(@seatoccpic, '')),
  `pc_profession` = TRIM(NULLIF(@pcprofession, '')),
  `bfr` = TRIM(NULLIF(@bfr, '')),
  `bfr_date` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@bfrdate, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `ft_as_of`= DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@ftasof, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `flight_crew_lchg_date` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@lchgdate, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `flight_crew_lchg_userid` = TRIM(NULLIF(@lchguserid, ''));

SELECT 'Importing Flight Crew detailed data';
DROP TABLE IF EXISTS `dt_flight_crew`;
CREATE TABLE `dt_flight_crew` (
  `ev_id` VARCHAR(14) NOT NULL,
  `aircraft_key` INT NOT NULL,
  `aircraft_id` VARCHAR(16) NOT NULL,
  `crew_no` TINYINT NOT NULL,
  `crew_id` VARCHAR(19) NOT NULL,
  `col_name` CHAR(20) NOT NULL,
  `code` CHAR(4)  NOT NULL,
  `dt_flight_crew_lchg_date` DATETIME DEFAULT NULL,
  `dt_flight_crew_lchg_userid` VARCHAR(18) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

LOAD DATA INFILE '/tmp/dt_flight_crew.csv' INTO TABLE `dt_flight_crew`
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@evid, @aircraftkey, @crewno, @colname, @code, @lchgdate, @lchguserid)
SET
  `ev_id` = TRIM(NULLIF(@evid, '')),
  `aircraft_key` = TRIM(NULLIF(@aircraftkey, '')),
  `aircraft_id` = CONCAT(@evid, '-', @aircraftkey),
  `crew_no` = TRIM(NULLIF(@crewno, '')),
  `crew_id` = CONCAT(@evid, '-', @aircraftkey, '-', @crewno),
  `col_name` = TRIM(NULLIF(@colname, '')),
  `code` = TRIM(NULLIF(@code, '')),
  `dt_flight_crew_lchg_date` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@lchgdate, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `dt_flight_crew_lchg_userid` = TRIM(NULLIF(@lchguserid, ''));

SELECT 'Importing Flight Time data';
DROP TABLE IF EXISTS `flight_time`;
CREATE TABLE `flight_time` (
  `ev_id` VARCHAR(14) NOT NULL,
  `aircraft_key` INT NOT NULL,
  `aircraft_id` VARCHAR(16) NOT NULL,
  `crew_no` TINYINT NOT NULL,
  `crew_id` VARCHAR(19) NOT NULL,
  `flight_type` CHAR(4) NOT NULL,
  `flight_craft` CHAR(4) NOT NULL,
  `flight_hours` REAL DEFAULT NULL,
  `flight_time_lchg_date` DATETIME DEFAULT NULL,
  `flight_time_lchg_userid` VARCHAR(18) DEFAULT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

LOAD DATA INFILE '/tmp/flight_time.csv' INTO TABLE `flight_time`
FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@evid, @aircraftkey, @crewno, @flighttype, @flightcraft, @flighthours, @lchgdate, @lchguserid)
SET
  `ev_id` = TRIM(NULLIF(@evid, '')),
  `aircraft_key` = TRIM(NULLIF(@aircraftkey, '')),
  `aircraft_id` = CONCAT(@evid, '-', @aircraftkey),
  `crew_no` = TRIM(NULLIF(@crewno, '')),
  `crew_id` = CONCAT(@evid, '-', @aircraftkey, '-', @crewno),
  `flight_type` = TRIM(NULLIF(@flighttype, '')),
  `flight_craft` = TRIM(NULLIF(@flightcraft, '')),
  `flight_hours` = TRIM(NULLIF(@flighthours, '')),
  `flight_time_lchg_date` = DATE_FORMAT(STR_TO_DATE(TRIM(NULLIF(@lchgdate, '')), '%m/%d/%Y'), '%Y-%m-%d'),
  `flight_time_lchg_userid` = TRIM(NULLIF(@lchguserid, ''));